### ISSUE TITLE
UI/IDE: feedback button seems slightly out of place in IDE

### ISSUE THREAD

**Issue by deansheather** [codercom/bugs#70]
**Describe the bug**
Feedback button appears slightly out of place in IDE view.

**To Reproduce**
1. Open the dashboard
2. Notice the positioning of the feedback button in the bottom left (correct positioning)
3. Open the IDE for any project
4. Notice the positioning of the feedback button in the bottom left (incorrect positioning)
5. Compare

**Expected behavior**
The button should be positioned correctly.

**Screenshots**
![Correct](https://awau.moe/19b8f2.png) (dashboard view - correct positioning)

vs.

![Incorrect](https://awau.moe/388a22.png) (IDE view - incorrect positioning)

**Additional context**
Reported via Zendesk. ```ticket # 305```

**Comment by jaymeramsay** [comment]
Thank you, Dean!

**Comment by jaymeramsay** [comment]
This issue has been fixed!

**Comment by deansheather** [comment]
Still seeing awkward positioning of the feedback button in the IDE:
![screenshot](https://awau.moe/cd5800.png)

Also reported by a user in Discord.

**Comment by coadler** [comment]
I still have this issue
![z](https://chito.ge/882072.png)
