### ISSUE TITLE
Container: can't compile C++ programs anymore with g++

### ISSUE THREAD

**Issue by deansheather** [codercom/bugs#97]
**Describe the bug**
Can't compile simple hello world C++ file anymore. Worked a few days ago. (I've compiled this program on Coder containers many times in the past to test user issues.)

Taken from https://github.com/leachim6/hello-world/blob/master/c/c%2B%2B.cpp:
```cpp
#include <iostream> // include API

using namespace std;

int main() // the main code portion of a C++ program
{
   cout << "Hello World" << endl;  //print Hello World on the screen 
   return 0; // conventional
}
```

```
# g++ test.cpp
In file included from /usr/include/x86_64-linux-gnu/c++/5/bits/os_defines.h:39:0,
                 from /usr/include/x86_64-linux-gnu/c++/5/bits/c++config.h:482,
                 from /usr/include/c++/5/iostream:38,
                 from test.cpp:1:
/usr/include/features.h:367:25: fatal error: sys/cdefs.h: No such file or directory
compilation terminated.
```

**To Reproduce**
1. Open IDE
2. Create a file called `test.cpp` with the contents above
3. Open terminal
4. `apt update && apt upgrade -y && apt install -y build-essential`
5. `g++ test.cpp`
6. Notice that g++ refuses to compile the file

Can reproduce. Tested on a freshly reset container as well.

**Expected behavior**
The file should compile correctly.

**Screenshots**
n/a

**Additional context**
Reported via Discord.

**Comment by akTwelve** [comment]
I'm having the same issue. Same repo steps, essentially the same code too.

**Comment by ammario** [comment]
Temporary fix: `apt-get --reinstall install libc6 libc6-dev`

**Comment by kylecarbs** [comment]
Fixed :+1:

**Comment by NGTmeaty** [comment]
I can still reproduce and it's still happening to users on the Discord.

**Comment by kylecarbs** [comment]
We handle the installation of g++ for users. I believe not installing those packages may solve that issue.
